/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/modern-apartment.glb 
Author: Visthétique (https://sketchfab.com/visthetique)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-apartment-1fbb649cd6624f2bb7b7d6e30c6533a5
Title: Modern Apartment
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/modern-apartment.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.853}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group scale={100}>
            <mesh geometry={nodes.BathroomFurnitures_Wood049_0.geometry} material={materials.Wood049} />
            <mesh geometry={nodes.BathroomFurnitures_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.BathroomFurnitures_Black001_0.geometry} material={materials['Black.001']} />
            <mesh geometry={nodes.BathroomFurnitures_Black001_0_1.geometry} material={materials['Black.001']} />
            <mesh geometry={nodes.BathroomFurnitures_Black001_0_2.geometry} material={materials['Black.001']} />
            <mesh geometry={nodes.BathroomFurnitures_Marble_014_0.geometry} material={materials.Marble_014} />
            <mesh geometry={nodes.BathroomFurnitures_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.BathroomFurnitures_White1_0_1.geometry} material={materials.White1} />
            <mesh geometry={nodes.BathroomFurnitures_M_1_Mat3d66_1341339_11_7439001_0.geometry} material={materials['M_1_Mat3d66_1341339_11_7439.001']} />
            <mesh geometry={nodes.BathroomFurnitures_M_1_Mat3d66_1341339_12_2128001_0.geometry} material={materials['M_1_Mat3d66_1341339_12_2128.001']} />
            <mesh geometry={nodes.BathroomFurnitures_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.BathroomFurnitures_Glass_0_1.geometry} material={materials.Glass} />
            <mesh geometry={nodes.BathroomFurnitures_M_1_Mat3d66_1341339_17_7081001_0.geometry} material={materials['M_1_Mat3d66_1341339_17_7081.001']} />
            <mesh geometry={nodes.BathroomFurnitures_M_1_Mat3d66_1341339_18_8295001_0.geometry} material={materials['M_1_Mat3d66_1341339_18_8295.001']} />
            <mesh geometry={nodes.BathroomFurnitures_DarkGray_0.geometry} material={materials.DarkGray} />
            <mesh geometry={nodes.BathroomFurnitures_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.BathroomFurnitures_Light_0.geometry} material={materials.Light} />
            <mesh geometry={nodes.BathroomFurnitures_M_10_Leaf_1001_0.geometry} material={materials['M_10_Leaf_1.001']} />
            <mesh geometry={nodes.BathroomFurnitures_M_10_Leaf_1001_0_1.geometry} material={materials['M_10_Leaf_1.001']} />
            <mesh geometry={nodes.BathroomFurnitures_Material_10001_0.geometry} material={materials['Material_10.001']} />
          </group>
          <group position={[1003.527, 252.576, 242.547]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.BathroomWashing_Wood049_0.geometry} material={materials.Wood049} />
            <mesh geometry={nodes.BathroomWashing_Gold_0.geometry} material={materials.Gold} />
            <mesh geometry={nodes.BathroomWashing_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.BathroomWashing_Secadora_0.geometry} material={materials.Secadora} />
            <mesh geometry={nodes.BathroomWashing_Lavadora_0.geometry} material={materials.Lavadora} />
            <mesh geometry={nodes.BathroomWashing_White1_0.geometry} material={materials.White1} />
          </group>
          <group scale={100}>
            <mesh geometry={nodes.Bed_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.Bed_White1_0_1.geometry} material={materials.White1} />
            <mesh geometry={nodes.Bed_White1_0_2.geometry} material={materials.White1} />
            <mesh geometry={nodes.Bed_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Bed_Cream_0.geometry} material={materials.Cream} />
            <mesh geometry={nodes.Bed_Plain_Grey_Texture_2669056_20cm001_0.geometry} material={materials['Plain_Grey_Texture_2669056_20cm.001']} />
            <mesh geometry={nodes.Bed_DarkGray_0.geometry} material={materials.DarkGray} />
            <mesh geometry={nodes.Bed_BlackMetal_0.geometry} material={materials.BlackMetal} />
            <mesh geometry={nodes.Bed_Plain_Natural_Sheer_2771559_20cm001_0.geometry} material={materials['Plain_Natural_Sheer_2771559_20cm.001']} />
          </group>
          <group scale={100}>
            <mesh geometry={nodes.BedDecors_Light_0.geometry} material={materials.Light} />
            <mesh geometry={nodes.BedDecors_Gold_0.geometry} material={materials.Gold} />
            <mesh geometry={nodes.BedDecors_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.BedDecors_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.BedDecors_TravelersStem001_0.geometry} material={materials['TravelersStem.001']} />
            <mesh geometry={nodes.BedDecors_Splitleaf3small001_0.geometry} material={materials['Splitleaf3small.001']} />
            <mesh geometry={nodes.BedDecors_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.BedDecors__4001_0.geometry} material={materials['4.001']} />
            <mesh geometry={nodes.BedDecors_Wood049_0.geometry} material={materials.Wood049} />
            <mesh geometry={nodes.BedDecors_Wood_Floor_039_0.geometry} material={materials.Wood_Floor_039} />
            <mesh geometry={nodes.BedDecors_Black001_0.geometry} material={materials['Black.001']} />
          </group>
          <group scale={100}>
            <mesh geometry={nodes.BedroomWardrobes_Wood049_0.geometry} material={materials.Wood049} />
            <mesh geometry={nodes.BedroomWardrobes_Chrome_0.geometry} material={materials.Chrome} />
          </group>
          <group position={[722.606, 194.225, 12.967]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[71.04, 71.04, 76.53]}>
            <mesh geometry={nodes.BookCase_Wood049_0.geometry} material={materials.Wood049} />
            <mesh geometry={nodes.BookCase_Gold_0.geometry} material={materials.Gold} />
            <mesh geometry={nodes.BookCase_Gold_0_1.geometry} material={materials.Gold} />
            <mesh geometry={nodes.BookCase_DarkGray_0.geometry} material={materials.DarkGray} />
            <mesh geometry={nodes.BookCase_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.BookCase_White1_0_1.geometry} material={materials.White1} />
            <mesh geometry={nodes.BookCase__45_0.geometry} material={materials.material} />
            <mesh geometry={nodes.BookCase_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.BookCase_Marble_014_0.geometry} material={materials.Marble_014_29} />
            <mesh geometry={nodes.BookCase_Book_Spine_1_0.geometry} material={materials.Book_Spine_1} />
            <mesh geometry={nodes.BookCase_Color_5_0.geometry} material={materials.Color_5} />
            <mesh geometry={nodes.BookCase_Color_6_0.geometry} material={materials.Color_6} />
            <mesh geometry={nodes.BookCase_leaf2_smaller_cleansadfasdfasdfasd_0.geometry} material={materials.leaf2_smaller_cleansadfasdfasdfasd} />
          </group>
          <group position={[-551.983, 40.924, -121.242]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cables_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Cables_White1_0.geometry} material={materials.White1} />
          </group>
          <group position={[-639.304, 97.116, -150.215]} scale={3.063}>
            <mesh geometry={nodes['Coffee+Maker_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['Coffee+Maker_White1_0'].geometry} material={materials.White1} />
            <mesh geometry={nodes['Coffee+Maker_Glass_0'].geometry} material={materials.Glass} />
            <mesh geometry={nodes['Coffee+Maker_Chrome_0'].geometry} material={materials.Chrome} />
            <mesh geometry={nodes['Coffee+Maker_Coffee_Maker_Material5_0'].geometry} material={materials.Coffee_Maker_Material5} />
          </group>
          <group position={[-339.445, 73.974, 166.77]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.CouchSet_Wood049_0.geometry} material={materials.Wood049} />
            <mesh geometry={nodes.CouchSet_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.CouchSet_White1_0_1.geometry} material={materials.White1} />
            <mesh geometry={nodes.CouchSet_White1_0_2.geometry} material={materials.White1} />
            <mesh geometry={nodes.CouchSet_DarkGray_0.geometry} material={materials.DarkGray} />
            <mesh geometry={nodes.CouchSet_Material_2_0.geometry} material={materials.Material_2} />
            <mesh geometry={nodes.CouchSet_Material_1_0.geometry} material={materials.Material_1} />
            <mesh geometry={nodes.CouchSet_Material_5_0.geometry} material={materials.Material_5} />
            <mesh geometry={nodes.CouchSet_Material_10002_0.geometry} material={materials['Material_10.002']} />
            <mesh geometry={nodes.CouchSet_Material_9_0.geometry} material={materials.Material_9} />
            <mesh geometry={nodes.CouchSet_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.CouchSet_GlassGreen_0.geometry} material={materials.GlassGreen} />
            <mesh geometry={nodes.CouchSet_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.CouchSet_texturatapete_sala_asdfasdf0as5f1065r10e51r0510e51es_0.geometry} material={materials.texturatapete_sala_asdfasdf0as5f1065r10e51r0510e51es} />
            <mesh geometry={nodes.CouchSet_caule_planta_fdsdfsdwssssssssssssssssssssssssssssssssssssssssss_0.geometry} material={materials.caule_planta_fdsdfsdwssssssssssssssssssssssssssssssssssssssssss} />
            <mesh geometry={nodes.CouchSet_folha_planta_hd_fdsfad0fas65df0a16s50r1e2a01s2df10asd1af5sd4f4w_0.geometry} material={materials.folha_planta_hd_fdsfad0fas65df0a16s50r1e2a01s2df10asd1af5sd4f4w} />
          </group>
          <group position={[1411.487, 318.923, -157.473]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[226.092, 64.012, 205.056]}>
            <mesh geometry={nodes.Curtatins_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Curtatins__97001_0.geometry} material={materials['97.001']} />
            <mesh geometry={nodes.Curtatins_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.Curtatins_White1_0_1.geometry} material={materials.White1} />
          </group>
          <group position={[16.988, 129.524, 180.207]} rotation={[-Math.PI / 2, 0, 0]} scale={105.028}>
            <mesh geometry={nodes.DiningTable001_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.DiningTable001_BlackMetal_0.geometry} material={materials.BlackMetal} />
            <mesh geometry={nodes.DiningTable001_Wood049_0.geometry} material={materials.Wood049} />
            <mesh geometry={nodes.DiningTable001_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.DiningTable001_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.DiningTable001_Gold_0.geometry} material={materials.Gold} />
          </group>
          <group position={[72.632, 77.983, -61.003]} rotation={[-Math.PI / 2, 0, -0.053]} scale={100}>
            <mesh geometry={nodes.Dishwasher001_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.Dishwasher001_Wood049_0.geometry} material={materials.Wood049} />
            <mesh geometry={nodes.Dishwasher001_DSI_46750_Screen001_0.geometry} material={materials['DSI_46750_Screen.001']} />
            <mesh geometry={nodes.Dishwasher001_DSI_46750_Door001_0.geometry} material={materials['DSI_46750_Door.001']} />
          </group>
          <group scale={100}>
            <mesh geometry={nodes.Door001_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.Door001_White1_0_1.geometry} material={materials.White1} />
            <mesh geometry={nodes.Door001_White1_0_2.geometry} material={materials.White1} />
            <mesh geometry={nodes.Door001_White1_0_3.geometry} material={materials.White1} />
            <mesh geometry={nodes.Door001_White1_0_4.geometry} material={materials.White1} />
            <mesh geometry={nodes.Door001_White1_0_5.geometry} material={materials.White1} />
            <mesh geometry={nodes.Door001_White1_0_6.geometry} material={materials.White1} />
            <mesh geometry={nodes.Door001_White1_0_7.geometry} material={materials.White1} />
            <mesh geometry={nodes.Door001_White1_0_8.geometry} material={materials.White1} />
            <mesh geometry={nodes.Door001_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Door001_Black_0_1.geometry} material={materials.Black} />
          </group>
          <group position={[-752.665, 41.721, -110.366]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[27.852, 19.388, 27.852]}>
            <mesh geometry={nodes.ElectricPlugs_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.ElectricPlugs_Black_0.geometry} material={materials.Black} />
          </group>
          <group position={[1532.464, 196.569, 510.751]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[96.383, 66.864, 96.093]}>
            <mesh geometry={nodes.EnteranceDoor_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.EnteranceDoor_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.EnteranceDoor_Wood0035_0.geometry} material={materials.Wood0035} />
          </group>
          <group position={[-674.271, 97.747, -98.6]} rotation={[-Math.PI / 2, 0, 1.402]} scale={100}>
            <mesh geometry={nodes.Flower_leaf2_smaller_cleansadfasdfasdfasd_0.geometry} material={materials.leaf2_smaller_cleansadfasdfasdfasd} />
            <mesh geometry={nodes.Flower_asdfasdfasdfasdf_0.geometry} material={materials.asdfasdfasdfasdf} />
            <mesh geometry={nodes.Flower_leaf1_smaller_cleanasdfasfasdfas_0.geometry} material={materials.leaf1_smaller_cleanasdfasfasdfas} />
            <mesh geometry={nodes.Flower_Materi0150160560156_0.geometry} material={materials.Materi0150160560156} />
            <mesh geometry={nodes.Flower_White1_0.geometry} material={materials.White1} />
          </group>
          <group position={[-112.178, 97.473, -106.729]} rotation={[-Math.PI / 2, 0, -0.044]} scale={[133.621, 100, 100]}>
            <mesh geometry={nodes.Hobs001_NightRiverBlack001_0.geometry} material={materials['NightRiverBlack.001']} />
            <mesh geometry={nodes.Hobs001_Base001_0.geometry} material={materials['Base.001']} />
          </group>
          <group position={[-111.451, 197.572, -110.058]} rotation={[-Math.PI / 2, 0, -1.63]} scale={27.483}>
            <mesh geometry={nodes.Hood_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Hood_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Hood_Light_0.geometry} material={materials.Light} />
            <mesh geometry={nodes.Hood_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.Hood_Chrome_0.geometry} material={materials.Chrome} />
          </group>
          <group position={[-607.008, 101.79, -109.499]} rotation={[-Math.PI / 2, 0, 2.218]} scale={100}>
            <mesh geometry={nodes.KDecor_Dip_Large_Mugs_001_0.geometry} material={materials.Dip_Large_Mugs_001} />
            <mesh geometry={nodes.KDecor_Silo_Canisters_001_0.geometry} material={materials.Silo_Canisters_001} />
            <mesh geometry={nodes.KDecor_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.KDecor_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.KDecor_Black_0_1.geometry} material={materials.Black} />
            <mesh geometry={nodes.KDecor_Poke_Cookbook_001_0.geometry} material={materials.Poke_Cookbook_001} />
            <mesh geometry={nodes.KDecor_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.KDecor_Label_Ficks_Margarita_001_0.geometry} material={materials.Label_Ficks_Margarita_001} />
            <mesh geometry={nodes.KDecor_Black001_0.geometry} material={materials['Black.001']} />
            <mesh geometry={nodes.KDecor_Fabrics0070001_0.geometry} material={materials['Fabrics0070.001']} />
            <mesh geometry={nodes.KDecor_Measuring_Cups_001_0.geometry} material={materials.Measuring_Cups_001} />
            <mesh geometry={nodes.KDecor_Wood0035_0.geometry} material={materials.Wood0035} />
            <mesh geometry={nodes.KDecor_Marble_014_0.geometry} material={materials.Marble_014_29} />
            <mesh geometry={nodes.KDecor_Faux_Monstera_Leaf_001_0.geometry} material={materials.Faux_Monstera_Leaf_001} />
            <mesh geometry={nodes.KDecor_Faux_Succulent_Stem_001_0.geometry} material={materials.Faux_Succulent_Stem_001} />
            <mesh geometry={nodes.KDecor_Glossy_Canyon_Ice_Bucke_001_0.geometry} material={materials.Glossy_Canyon_Ice_Bucke_001} />
            <mesh geometry={nodes.KDecor_Vase_Black_Kitchen_Utensils_001_0.geometry} material={materials.Vase_Black_Kitchen_Utensils_001} />
            <mesh geometry={nodes.KDecor_Wood049_0.geometry} material={materials.Wood049} />
            <mesh geometry={nodes.KDecor_Chrome_0.geometry} material={materials.Chrome} />
          </group>
          <group position={[-501.115, 60.525, 284.376]} rotation={[-Math.PI / 2, 0, -0.679]} scale={14.805}>
            <mesh geometry={nodes.MacBook_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.MacBook_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.MacBook_Keylight_0.geometry} material={materials.Keylight} />
            <mesh geometry={nodes.MacBook_touchbar_0.geometry} material={materials.touchbar} />
            <mesh geometry={nodes.MacBook_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.MacBook_Screen_Shot_2016_12_26_at_8_02_30_PM_0.geometry} material={materials.Screen_Shot_2016_12_26_at_8_02_30_PM} />
          </group>
          <group position={[485.331, 105.228, -28.808]} rotation={[-Math.PI / 2, 0, 0]} scale={34.106}>
            <mesh geometry={nodes['Office+Desk_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['Office+Desk_Fabrics0070001_0'].geometry} material={materials['Fabrics0070.001']} />
            <mesh geometry={nodes['Office+Desk_BlackMetal_0'].geometry} material={materials.BlackMetal} />
            <mesh geometry={nodes['Office+Desk_Gold_0'].geometry} material={materials.Gold} />
            <mesh geometry={nodes['Office+Desk_Chrome_0'].geometry} material={materials.Chrome} />
            <mesh geometry={nodes['Office+Desk_Screen_0'].geometry} material={materials.Screen} />
          </group>
          <group position={[463.884, 47.717, -76.444]} rotation={[-Math.PI / 2, 0, 1.928]} scale={108.384}>
            <mesh geometry={nodes.OficeDecors_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.OficeDecors_Black_0_1.geometry} material={materials.Black} />
            <mesh geometry={nodes.OficeDecors_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.OficeDecors_blueprint_2_small_0.geometry} material={materials.blueprint_2_small} />
            <mesh geometry={nodes.OficeDecors_Light_0.geometry} material={materials.Light} />
            <mesh geometry={nodes.OficeDecors_Gold_0.geometry} material={materials.Gold} />
            <mesh geometry={nodes.OficeDecors_Carpet_0.geometry} material={materials.Carpet} />
          </group>
          <group position={[73.886, 224.312, -48.75]} rotation={[-Math.PI / 2, 0, -0.062]} scale={100}>
            <mesh geometry={nodes.Oven001_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Oven001_Logo001_0.geometry} material={materials['Logo.001']} />
            <mesh geometry={nodes.Oven001_FrontDown001_0.geometry} material={materials['FrontDown.001']} />
            <mesh geometry={nodes.Oven001_FrontTop001_0.geometry} material={materials['FrontTop.001']} />
            <mesh geometry={nodes.Oven001_FrontPanel001_0.geometry} material={materials['FrontPanel.001']} />
          </group>
          <group position={[302.51, 188.557, 321.025]} rotation={[-Math.PI / 2, 0, 0]} scale={[54.401, 28.976, 54.401]}>
            <mesh geometry={nodes.Paintings_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Paintings_Painting_0.geometry} material={materials.Painting} />
            <mesh geometry={nodes.Paintings_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Paintings_Painting5_0.geometry} material={materials.Painting5} />
            <mesh geometry={nodes.Paintings_Painting3_0.geometry} material={materials.Painting3} />
            <mesh geometry={nodes.Paintings_Painting4_0.geometry} material={materials.Painting4} />
            <mesh geometry={nodes.Paintings_Painting2_0.geometry} material={materials.Painting2} />
          </group>
          <group position={[496.001, 111.393, -146.908]} rotation={[-Math.PI / 2, 0, 0]} scale={80.606}>
            <mesh geometry={nodes.PenHolder_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.PenHolder_Fencing_Construction_0.geometry} material={materials.Fencing_Construction} />
            <mesh geometry={nodes.PenHolder_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.PenHolder_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.PenHolder_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.PenHolder__Black__0.geometry} material={materials.Black_78} />
          </group>
          <group scale={100}>
            <mesh geometry={nodes.Plane002_Black001_0.geometry} material={materials['Black.001']} />
            <mesh geometry={nodes.Plane002_SprayedWallTexture_0.geometry} material={materials.SprayedWallTexture} />
            <mesh geometry={nodes.Plane002_1500_0.geometry} material={materials['1500']} />
            <mesh geometry={nodes.Plane002_Wood0035_0.geometry} material={materials.Wood0035} />
            <mesh geometry={nodes.Plane002_PavingStones128_0.geometry} material={materials.PavingStones128} />
            <mesh geometry={nodes.Plane002_Wood_Floor_039_0.geometry} material={materials.Wood_Floor_039} />
            <mesh geometry={nodes.Plane002_Marble_014_0.geometry} material={materials.Marble_014} />
            <mesh geometry={nodes.Plane002_Gold_0.geometry} material={materials.Gold} />
            <mesh geometry={nodes.Plane002_Marble_015_0.geometry} material={materials.Marble_015} />
            <mesh geometry={nodes.Plane002_White1_0.geometry} material={materials.White1} />
          </group>
          <group scale={100}>
            <mesh geometry={nodes.Plane004_Wood049_0.geometry} material={materials.Wood049} />
            <mesh geometry={nodes.Plane004_Chrome_0.geometry} material={materials.Chrome} />
          </group>
          <group position={[926.505, 85.99, 355.898]} rotation={[-Math.PI / 2, 0, 3.017]} scale={32.337}>
            <mesh geometry={nodes.Plants_Material__7_0.geometry} material={materials.Material__7} />
            <mesh geometry={nodes.Plants_Material__7_0_1.geometry} material={materials.Material__7} />
            <mesh geometry={nodes.Plants_Material__7_0_2.geometry} material={materials.Material__7} />
            <mesh geometry={nodes.Plants_Material__7_0_3.geometry} material={materials.Material__7} />
            <mesh geometry={nodes.Plants_Material__7_0_4.geometry} material={materials.Material__7} />
            <mesh geometry={nodes.Plants_Material__7_0_5.geometry} material={materials.Material__7} />
            <mesh geometry={nodes.Plants_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.Plants_White1_0_1.geometry} material={materials.White1} />
            <mesh geometry={nodes.Plants_BlackMetal_0.geometry} material={materials.BlackMetal} />
            <mesh geometry={nodes.Plants_Material__5_0.geometry} material={materials.Material__5} />
          </group>
          <group position={[181.763, 107.295, -46.769]} rotation={[-Math.PI / 2, 0, -0.053]} scale={100}>
            <mesh geometry={nodes.Refrigator001_BrushedMetalSeamless001_0.geometry} material={materials['BrushedMetalSeamless.001']} />
            <mesh geometry={nodes.Refrigator001_Aluminum001_0.geometry} material={materials['Aluminum.001']} />
            <mesh geometry={nodes.Refrigator001_FrontBlack001_0.geometry} material={materials['FrontBlack.001']} />
            <mesh geometry={nodes.Refrigator001_Black_0.geometry} material={materials.Black} />
          </group>
          <group position={[1116.199, 24.923, 223.641]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Shoes_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.Shoes_White1_0_1.geometry} material={materials.White1} />
            <mesh geometry={nodes.Shoes_Right2_0.geometry} material={materials.Right2} />
            <mesh geometry={nodes.Shoes_M_2a_0.geometry} material={materials.M_2a} />
            <mesh geometry={nodes.Shoes_Snkrs01_0.geometry} material={materials.Snkrs01} />
            <mesh geometry={nodes.Shoes_M_Med_CycloneSpace_T3_BodyMASTER_Inst_0.geometry} material={materials.M_Med_CycloneSpace_T3_BodyMASTER_Inst} />
            <mesh geometry={nodes.Shoes_DarkGray_0.geometry} material={materials.DarkGray} />
          </group>
          <group position={[0, 9.696, 0]} scale={100}>
            <mesh geometry={nodes.Sink_Out001_0.geometry} material={materials['Out.001']} />
            <mesh geometry={nodes.Sink_Sink4Metal001_0.geometry} material={materials['Sink4Metal.001']} />
            <mesh geometry={nodes.Sink_Sink2Metal001_0.geometry} material={materials['Sink2Metal.001']} />
            <mesh geometry={nodes.Sink_Hole001_0.geometry} material={materials['Hole.001']} />
            <mesh geometry={nodes.Sink_Faucet3001_0.geometry} material={materials['Faucet3.001']} />
          </group>
          <group position={[-711.638, 69.548, 59.907]} rotation={[-Math.PI / 2, 0, 1.702]} scale={12.369}>
            <mesh geometry={nodes.StandSpeaker_Fabrics0070001_0.geometry} material={materials['Fabrics0070.001']} />
            <mesh geometry={nodes.StandSpeaker_Black_0.geometry} material={materials.Black} />
          </group>
          <group position={[-760.992, 172.567, 187.365]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Windows_Window_Frame_0.geometry} material={materials.Window_Frame} />
            <mesh geometry={nodes.Windows_Glass_0.geometry} material={materials.Glass} />
          </group>
          <group position={[-134.125, 214.153, 27.782]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Zebra_Curtains_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.Zebra_Curtains_tecido_0.geometry} material={materials.tecido} />
          </group>
          <group position={[609.549, 100.344, -114.741]} rotation={[-Math.PI / 2, 0, -2.574]} scale={76.131}>
            <mesh geometry={nodes.iMac_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.iMac_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.iMac_Screen_0.geometry} material={materials.Screen} />
          </group>
          <group position={[1629.748, 31.014, 467.358]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={19.142}>
            <mesh geometry={nodes.shoeRack_White1_0.geometry} material={materials.White1} />
            <mesh geometry={nodes.shoeRack_Wood049_0.geometry} material={materials.Wood049} />
            <mesh geometry={nodes.shoeRack_CADEIRA_JANTAR_ESTOFADA___TECIDO_0.geometry} material={materials.CADEIRA_JANTAR_ESTOFADA___TECIDO} />
            <mesh geometry={nodes.shoeRack_Color_D04_0.geometry} material={materials.Color_D04} />
          </group>
          <mesh geometry={nodes.Apple_Adaptor_White1_0.geometry} material={materials.White1} position={[-193.179, 40.137, 500.713]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={113.864} />
          <mesh geometry={nodes.Baseboard__0.geometry} material={materials.Baseboard__0} position={[112.567, 26.743, 280.279]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.BathroomFurnitures001_White1_0.geometry} material={materials.White1} scale={100} />
          <mesh geometry={nodes.BathroomWashing001_White1_0.geometry} material={materials.White1} position={[1003.527, 252.576, 242.547]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.BedroomRug_Fabrics0070001_0.geometry} material={materials['Fabrics0070.001']} scale={100} />
          <mesh geometry={nodes.Plane007_Wood049_0.geometry} material={materials.Wood049} position={[0, 9.696, 0]} scale={100} />
          <mesh geometry={nodes.Toilet_White1_0.geometry} material={materials.White1} scale={100} />
          <mesh geometry={nodes.kitchenblind_Black_0.geometry} material={materials.Black} position={[-134.653, 231.04, -159.938]} scale={[49.555, 18.225, 42.853]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/modern-apartment.glb')
